- hosts: localhost
  vars_files: "{{ playbook_dir }}/config/defaults.yml"
  tasks:
    - name: Clone the openshift-ansible repo
      git:
        repo: 'https://github.com/openshift/openshift-ansible'
        dest: "{{ workspace }}/openshift-ansible"
        version: "release-{{ (lookup('env', 'OPENSHIFT_VERSION') or 'v3.11')[1:] }}"
        force: yes
