---
- name: Deploy NFS EC2 instance
  hosts: localhost
  roles:
    - ec2_provision
  vars_files:
    - "{{ playbook_dir }}/config/defaults.yml"

- name: Add NFS EC2 instance host to in memory inventory
  hosts: localhost
  tasks:
    - add_host:
        name: "{{ ec2_instance_ip }}"
        group: nfs_servers
        ansible_user: "{{ ec2_ssh_user }}"
        ansible_ssh_private_key_file: "{{ ec2_private_key_file }}"
  vars_files:
    - "{{ playbook_dir }}/config/defaults.yml"

- name: Configure NFS EC2 instance
  hosts: nfs_servers
  roles:
    - nfs_config
  vars:
    ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
