- name: Setup RHEL subscription for openshift
  redhat_subscription:
    state: present
    username: "{{ sub_user }}"
    password: "{{ sub_pass }}"
    auto_attach: true
    force_register: true

- name: Disable all RHSM repositories
  rhsm_repository:
    name: '*'
    state: disabled

- name: Enable OKD repos
  rhsm_repository:
    name:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - "rhel-7-server-ose-{{ ocp_version[1:] }}-rpms"
      - "rhel-7-fast-datapath-rpms"
      - rhel-7-server-ansible-2.6-rpms
    state: enabled

- name: Update installed packages
  yum:
    name: '*'
    state: latest

- name: Reboot the machine
  reboot:
      pre_reboot_delay: 5
      test_command: whoami
      reboot_timeout: 600
