# # Source: https://gitlab.sat.engineering.redhat.com/rhci/vm_env/tree/master/openshift/aos-3.11
# # Creator: Jason Montleon - https://gitlab.sat.engineering.redhat.com/jmontleo

---
- name: Setup RHEL subscription for openshift
  redhat_subscription:
    state: present
    username: "{{ sub_user }}"
    password: "{{ sub_pass }}"
    auto_attach: true
    force_register: true

- name: Disable all RHSM repositories
  rhsm_repository:
    name: '*'
    state: disabled

- name: Enable OKD repos
  rhsm_repository:
    name:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - "rhel-7-server-ose-{{ ocp_version[1:] }}-rpms"
      - rhel-7-server-ansible-2.6-rpms
    state: enabled

- name: Update installed packages
  yum:
    name: '*'
    state: latest

- name: Reboot the machine
  reboot:
      pre_reboot_delay: 5
      test_command: whoami
      reboot_timeout: 600

- name: Configure docker storage
  copy:
    content: |
              STORAGE_DRIVER=""
    dest: /etc/sysconfig/docker-storage-setup
  become: true
