- name: Add openshift all-in-one inventory
  add_host:
    name: "{{ ec2_instance_ip }}.xip.io"
    groups:
      - masters
      - nodes
      - OSEv3
      - etcd
    ansible_become: yes
    ansible_user: ec2-user
    ansible_ssh_private_key_file: "{{ ec2_private_key_file }}"

    # AWS provider setup
    openshift_cloudprovider_kind: aws
    openshift_clusterid: "{{ rand_id }}"
    openshift_cloudprovider_aws_access_key: "{{ aws_access_key_id }}"
    openshift_cloudprovider_aws_secret_key: "{{ aws_secret_access_key }}"

    os_sdn_network_plugin_name: 'redhat/openshift-ovs-multitenant'
    ansible_service_broker_install: false
    openshift_deployment_type: origin
    openshift_disable_check: 'disk_availability,memory_availability,docker_storage'
    openshift_public_hostname: "{{ ec2_instance_ip }}.xip.io"
    openshift_public_ip: "{{ ec2_instance_ip }}"
    openshift_master_cluster_public_hostname: "{{ ec2_instance_ip }}.xip.io"
    openshift_master_default_subdomain: "apps.{{ ec2_instance_ip }}.xip.io"
    openshift_master_identity_providers:
      - name: allow_all
        login: true
        challenge: true
        kind: AllowAllPasswordIdentityProvider
    openshift_schedulable: true
    os_update: true
    openshift_release: "{{ ocp_version }}"
    openshift_portal_net: 172.30.0.0/16
    openshift_image_tag: "v{{ ocp_version }}"
    openshift_node_groups:
    - name: 'node-config-all-in-one'
      labels:
      - 'node-role.kubernetes.io/master=true'
      - 'node-role.kubernetes.io/infra=true'
      - 'node-role.kubernetes.io/compute=true'
    openshift_node_group_name: "node-config-all-in-one"
