- name: copy kubeconfig to specified location
  copy:
    src: "{{ source_kubeconfig }}"
    dest: "{{ target_kubeconfig }}"
    remote_src: true

- debug:
    msg: "Backup of '{{ source_kubeconfig }}' is stored in '{{ target_kubeconfig }}'"
