# default common variables for mig-ci roles/plays

# Jenkins WORKSPACE or assume parent dir
workspace: "{{ lookup('env', 'WORKSPACE') or '../'}}"

# AWS / EC2 related
aws_access_key_id: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
aws_secret_access_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
ec2_region: "{{ lookup('env', 'EC2_REGION') or lookup('env', 'AWS_REGION') or 'us-east-1' }}"
ec2_key: "{{ lookup('ENV', 'EC2_KEY') or 'ci' }}"
ec2_private_key_file: "{{ workspace }}/keys/{{ ec2_key }}.pem"
ec2_ssh_user: "ec2-user"

cluster_version: "{{ lookup('env', 'CLUSTER_VERSION') or '4'}}"
oc_binary: "{{ workspace }}/bin/oc"
ocp3_version: "{{ lookup('env', 'OCP3_VERSION') or 'v3.11' }}"
ocp4_version: "{{ lookup('env', 'OCP4_VERSION') or 'v4.1' }}"

default_kube_location: "{{ workspace }}/kubeconfigs"
default_kubeconfig: "{{ lookup('env', 'KUBECONFIG') or default_kube_location + '/kubeconfig' }}"
ocp3_kubeconfig: "{{ default_kube_location }}/ocp-{{ ocp3_version }}-kubeconfig"
ocp4_kubeconfig: "{{ default_kube_location }}/ocp-{{ ocp4_version }}-kubeconfig"
