ocp_version: "{{ lookup('env', 'CLUSTER_VERSION') or '3.11' }}"
aws_name_suffix: "aws-ocp-{{ ocp_version }}"
sub_user: "{{ lookup('env', 'SUB_USER') or 'undefined' }}"
sub_pass: "{{ lookup('env', 'SUB_PASS') or 'undefined' }}"
aws_tags: "{{ {'kubernetes.io/cluster/' ~ rand_id: 'owned', 'clusterid': rand_id } }}"
