- name: Obtain NFS instance IP
  import_role:
    name: ec2_provision
    tasks_from: get_ip

- name: Remove existing PVs
  shell: "for i in $({{ oc_binary }} get pv --no-headers | awk '{ print $1 }'); do {{ oc_binary }} delete pv $i; done"
  tags:
    - remove_exisitng_pvs

- name: Template the PV resources
  template:
    src: "pv.yml.j2"
    dest: "{{ role_path }}/files/pv.yml"

- name: Create NFS PVs
  shell: "{{ oc_binary }} create -f {{ role_path }}/files/pv.yml"

- name: Remove template tmp file
  file:
    state: absent
    path: "{{ role_path }}/files/pv.yml"
