- name: check if config exists
  stat:
    path: "{{ playbook_dir }}/install-config.yaml"
  register: p

- name: check if aws config dir exists
  stat:
    path: "{{ ansible_env.HOME }}/.aws"
  register: aws_creds_dir

- name: check if aws credentials exist
  stat:
    path: "{{ ansible_env.HOME }}/.aws/credentials"
  register: aws_creds_file

- name: fail if config doesn't exist
  fail:
    msg: "install-config.yaml not found in current dir"
  when: p.stat.exists == false and generate_config == false

- name: check if openshift installer exists
  stat:
    path: "{{ playbook_dir }}/openshift-install"
  register: install

- name: check if there is an instance running before creating a new one
  stat:
    path: "{{ playbook_dir }}/terraform.tfvars"
  register: terraform

- name: delete old deployment
  shell: "{{ playbook_dir }}/openshift-install destroy cluster"
  when: install.stat.exists == true and terraform.stat.exists == true

- name: template install file
  template:
    src: install-config.yaml.j2
    dest: "{{ playbook_dir }}/install-config.yaml"
  when: generate_config|bool == true and p.stat.exists == false

- name: create aws creds dir
  file:
    path: "{{ ansible_env.HOME }}/.aws"
    state: directory
  when: aws_creds_dir.stat.exists == false

- name: template aws creds
  template:
    src: credentials.j2
    dest: "{{ ansible_env.HOME }}/.aws/credentials"
  when: aws_creds_file.stat.exists == false
